---
- name: Install PHP zip extension
  apt:
    pkg: "php{{ composer_php_version }}-zip"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
    warn: no

- name: Update Composer to latest version
  command: composer self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated

- name: Install Composer global packages
  composer:
    command: 'global require "{{ item.name }}={{ item.version }}"'
    prefer_dist: yes
    working_dir: /
  with_items: "{{ composer_global_packages }}"

- include_tasks: vagrant.yml
  when: vagrant and composer_create_swap
